OPTIONS (ERRORS=50)
LOAD DATA 
INFILE '/Users/kagoshin/tutorial/plsql/exportData/EMP_DATA_TABLE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "SYSTEM"."EMP"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"EMPNO" ,
"ENAME" CHAR (10),
"JOB" CHAR (9),
"MGR" ,
"HIREDATE" DATE "YYYY-MM-DD HH24:MI:SS" ,
"SAL" ,
"COMM" ,
"DEPTNO" )
